/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Syahrul
 */
public class pt5 extends javax.swing.JFrame {

    /**
     * Creates new form pt5
     */
    public pt5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        L = new javax.swing.JRadioButton();
        P = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pegawaiTF = new javax.swing.JTextField();
        nipTF = new javax.swing.JTextField();
        gajiTF = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jumlahAnakTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tunjanganAnakTF = new javax.swing.JTextField();
        tunjanganIstriTF = new javax.swing.JTextField();
        tunjanganJabatanTF = new javax.swing.JTextField();
        hutangKaryawanTF = new javax.swing.JTextField();
        totalTunjanganTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        infakCBX = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DAFTAR GAJI KARYAWAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PT. Muhamad Syahrul Irfan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel3.setText("Nama Pegawai");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 110, -1, -1));

        jLabel4.setText("NIP");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 151, -1, -1));

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 196, -1, -1));

        buttonGroup1.add(L);
        L.setText("Laki-Laki");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        jPanel1.add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 192, 98, -1));

        buttonGroup1.add(P);
        P.setText("Perempuan");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        jPanel1.add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 233, 98, -1));

        jLabel6.setText("Bagian");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 277, -1, -1));

        jLabel7.setText("Gaji Pokok");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 317, -1, -1));
        jPanel1.add(pegawaiTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 115, -1));
        jPanel1.add(nipTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 115, -1));

        gajiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiTFActionPerformed(evt);
            }
        });
        jPanel1.add(gajiTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 115, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Bagian", "Keuangan", "HRD", "Administrasi" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 115, -1));

        jLabel8.setText("Tunjangan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 110, -1, -1));

        jLabel9.setText("Jumlah Anak");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel10.setText("Tunjangan Anak");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 151, -1, -1));

        jLabel11.setText("Tunjangan Istri");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 196, -1, -1));

        jLabel12.setText("Tunjangan Jabatan");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 237, -1, -1));

        jLabel13.setText("Total Tunjangan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 286, -1, -1));

        jLabel14.setText("Hutang Karyawan");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 343, -1, -1));

        jumlahAnakTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahAnakTFActionPerformed(evt);
            }
        });
        jPanel1.add(jumlahAnakTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 107, 100, -1));

        jLabel15.setText("Orang");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        tunjanganAnakTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjanganAnakTFActionPerformed(evt);
            }
        });
        jPanel1.add(tunjanganAnakTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 148, 100, -1));

        tunjanganIstriTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjanganIstriTFActionPerformed(evt);
            }
        });
        jPanel1.add(tunjanganIstriTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 193, 100, -1));

        tunjanganJabatanTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjanganJabatanTFActionPerformed(evt);
            }
        });
        jPanel1.add(tunjanganJabatanTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 234, 100, -1));
        jPanel1.add(hutangKaryawanTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 340, 100, -1));

        totalTunjanganTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTunjanganTFActionPerformed(evt);
            }
        });
        jPanel1.add(totalTunjanganTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 283, 100, -1));

        Output.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Output);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 414, 800, 92));

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, -1));

        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 70, -1));

        infakCBX.setText("Infak");
        jPanel1.add(infakCBX, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 362, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
       
        if (combo.getSelectedIndex()==0){
            gajiTF.setText("");
            tunjanganJabatanTF.setText("");
        }else if (combo.getSelectedIndex()==1){
            gajiTF.setText("2500000");
            tunjanganJabatanTF.setText("75000");
        }else if (combo.getSelectedIndex()==2){
            gajiTF.setText("2100000");
            tunjanganJabatanTF.setText("63000");
        }else{
            gajiTF.setText("1800000");
            tunjanganJabatanTF.setText("54000");
        }
        
        
    }//GEN-LAST:event_comboActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
        if (L.isSelected()){
            tunjanganIstriTF.setText("1000000");
        }
        
    }//GEN-LAST:event_LActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
        if (P.isSelected()){
            tunjanganIstriTF.setText("0");
        }
        
    }//GEN-LAST:event_PActionPerformed

    private void gajiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiTFActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_gajiTFActionPerformed

    private void tunjanganAnakTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjanganAnakTFActionPerformed
        // TODO add your handling code here:
        
        
    
    }//GEN-LAST:event_tunjanganAnakTFActionPerformed

    private void jumlahAnakTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahAnakTFActionPerformed
        // TODO add your handling code here:
             int JumlahAnak = Integer.parseInt(jumlahAnakTF.getText());
        if (JumlahAnak<=2){
            tunjanganAnakTF.setText("300000");
        }else{
            tunjanganAnakTF.setText("800000");
        }
        
    }//GEN-LAST:event_jumlahAnakTFActionPerformed

    private void tunjanganIstriTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjanganIstriTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunjanganIstriTFActionPerformed

    private void tunjanganJabatanTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjanganJabatanTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunjanganJabatanTFActionPerformed

    private void totalTunjanganTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTunjanganTFActionPerformed
        // TODO add your handling code here:
        double gajiPokok = Double.parseDouble(gajiTF.getText());
        double jumlahAnak = Double.parseDouble(jumlahAnakTF.getText());
        double tunjanganAnak = Double.parseDouble(tunjanganAnakTF.getText());
        double tunjanganIstri = Double.parseDouble(tunjanganIstriTF.getText());
        double tunjanganJabatan = Double.parseDouble(tunjanganJabatanTF.getText());
        int totalTunjangan = (int)(tunjanganAnak + tunjanganIstri + tunjanganJabatan);
        totalTunjanganTF.setText(""+totalTunjangan);
        
    }//GEN-LAST:event_totalTunjanganTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NIP");
    model.addColumn("Nama");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Bagian");
    model.addColumn("Gaji Pokok");
    model.addColumn("Total Tunjangan");
    model.addColumn("Hutang Karyawan");
    model.addColumn("Gaji Bersih");
    Output.setModel(model);
    String nipValue = nipTF.getText();
    String namapegawaiValue = pegawaiTF.getText();
    String jkValue = L.isSelected() ? "Laki - Laki" : "Perempuan";
    String bagianValue = (String)combo.getSelectedItem();
    String gapokValue = gajiTF.getText();
    String ttValue = totalTunjanganTF.getText();
    String hutangk = hutangKaryawanTF.getText();
    
    double gajiPokok = Double.parseDouble(gajiTF.getText());
    double tt = Double.parseDouble(totalTunjanganTF.getText());
    double ppn = 0.1 * (gajiPokok + tt);
        double infak = 0;
        if (infakCBX.isSelected()){
            infak = 50000;
        }else{
            infakCBX.setSelected(false);
        }
        int gajibersih = (int)(gajiPokok + tt - ppn - infak);
        
    Object[] rowData = {
        nipValue,namapegawaiValue,jkValue,bagianValue,gapokValue,ttValue,hutangk,gajibersih
    };
    model = (DefaultTableModel) Output.getModel();
    model.addRow(rowData);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pegawaiTF.setText("");
        nipTF.setText("");
        gajiTF.setText("");
        jumlahAnakTF.setText("");
        tunjanganAnakTF.setText("");
        tunjanganIstriTF.setText("");
        tunjanganJabatanTF.setText("");
        totalTunjanganTF.setText("");
        hutangKaryawanTF.setText("");
        buttonGroup1.clearSelection();
        infakCBX.setSelected(false);
        combo.setSelectedIndex(0);
        DefaultTableModel model = (DefaultTableModel)Output.getModel();
        int selectedRow = Output.getSelectedRow();
        if (selectedRow !=-1){
        model.removeRow(selectedRow);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pt5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pt5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pt5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pt5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pt5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton L;
    private javax.swing.JTable Output;
    private javax.swing.JRadioButton P;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combo;
    private javax.swing.JTextField gajiTF;
    private javax.swing.JTextField hutangKaryawanTF;
    private javax.swing.JCheckBox infakCBX;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahAnakTF;
    private javax.swing.JTextField nipTF;
    private javax.swing.JTextField pegawaiTF;
    private javax.swing.JTextField totalTunjanganTF;
    private javax.swing.JTextField tunjanganAnakTF;
    private javax.swing.JTextField tunjanganIstriTF;
    private javax.swing.JTextField tunjanganJabatanTF;
    // End of variables declaration//GEN-END:variables
}
